repos:
-   repo: local
    hooks:
    -   id: validate-polls
        name: Validate poll entries
        entry: python presidentielles/validation.py
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
    -   id: validate-results
        name: Validate election results entries
        entry: python resultats/validation.py
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
