repos:
-   repo: local
    hooks:
    -   id: validate-polls-2022
        name: Validate polls for 2022 presidential election
        entry: python presidentielles/validation.py
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
