name: "Validate data"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install python packages
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - uses: pre-commit/action@v2.0.0
